### ISSUE TITLE
SampleServerClientTCP broken?

### ISSUE THREAD

**Issue by raymondbh** [Apollo3zehn/FluentModbus#102]
Just testing your modbus library (that looks very good at first glance), but I just get "TCP connection closed unexpectedly" what ever I do. Tried two different computers and added firewall rules and everything I can think of...

![bilde](https://github.com/Apollo3zehn/FluentModbus/assets/4389846/67ba3cb3-57b1-4860-b2d0-55d805c8fc4d)

SampleServerClientRTU seems to work just fine :)

**Comment by raymondbh** [comment]
Ok, I figured it out, seems the client unitiIdentifier set to 0xFF in the sample does not work. I set it to 0 and it was fine :) 

//var unitIdentifier = 0xFF;
var unitIdentifier = 0x00;

![bilde](https://github.com/Apollo3zehn/FluentModbus/assets/4389846/23200342-ba38-4b66-857b-d1c4c9f18d42)

**Comment by Apollo3zehn** [comment]
Thank you for pointing that out, I just fixed it
