### ISSUE TITLE
Reconnections around midnight

### ISSUE THREAD

**Issue by wartek69** [Apollo3zehn/FluentModbus#110]
Hi,
I'm using your library to communicate with several modbus TCP servers. All works fine but I started to notice that around midnight I have a reconnection to all the modbus TCP servers.
The Modbus TCP servers I'm connecting with are plc devices, simulator written using python and embedded devices. I see this behavior with all of them.
Initially I thought it was my network, but the simulators are running on the same machine as the Modbus TCP clients in the same docker network.
Has anyone encountered a similar issue or can point me in the right direction for debugging?
Br
Alex

**Comment by Apollo3zehn** [comment]
Hi Alex,

FluentModbus has no time-specific components which could explain that behavior and I have never heard of any similar behavior. You could record the network traffic with Wireshark or tshark and then try to find why the connection drops.
