### ISSUE TITLE
Signals, RTS, DTR, CTS ???

### ISSUE THREAD

**Issue by Seba131** [Apollo3zehn/FluentModbus#114]
Good morning, is there a chance to add support for RTS, DTR, CTS signals? They would be very helpful to me.

**Comment by Apollo3zehn** [comment]
Hi, you can use your self-managed SerialPort by doing the following:

```cs
var serialPort = new SerialPort("COM1")
{
    DtrEnable = true,
    RtsEnable = true
};

serialPort.Open();

client.Initialize(
    new ModbusRtuSerialPort(serialPort), 
    ModbusEndianness.LittleEndian);
```

**Comment by Seba131** [comment]
```
public ModbusRtuClient modbusRtu = new ModbusRtuClient();

modbusRtu.BaudRate = 9600;
itp...
```
No option to select DTR, CTS....

![DTR](https://github.com/Apollo3zehn/FluentModbus/assets/60814322/7a0e4e5d-8c15-4f77-884e-ec5bc9356a11)

**Comment by Apollo3zehn** [comment]
I am sorry, my example above missed the creation of the `ModbusRtuClient`:

Here is a better sample now:

```cs
var serialPort = new SerialPort("COM1");
var client = new ModbusRtuClient();

client.Initialize(
    new ModbusRtuSerialPort(serialPort), 
    ModbusEndianness.LittleEndian);

serialPort.Open();

serialPort.DtrEnable = true;
serialPort.RtsEnable = true;
```

As long as you have control over the instantiation of `ModbusRtuClient` the code sample should work. Or do you encounter other problems I did no cover in my answer (I did not fully understand your last post so I am not sure)?

**Comment by Seba131** [comment]
ok. It works.
