### ISSUE TITLE
Unable to create RTU Client

### ISSUE THREAD

**Issue by captmomo** [Apollo3zehn/FluentModbus#25]
![image](https://user-images.githubusercontent.com/25576022/71335669-c9cd3f80-257e-11ea-91af-99c678fc08f1.png)
Hi, I'm trying to create a RTU client but the constructor doesn't accept a string.

**Comment by captmomo** [comment]
Ok, it's the documentation. It should be corrected to ModbusRtuClient.  
  

![image](https://user-images.githubusercontent.com/25576022/71335726-1749ac80-257f-11ea-8140-4496b2ea632d.png)

**Comment by Apollo3zehn** [comment]
Thanks, I'll correct it later today! It's a classical copy paste error in the documentation ...

**Comment by Apollo3zehn** [comment]
Fixed!
