### ISSUE TITLE
Doesn't work on Linux in .Net Core

### ISSUE THREAD

**Issue by BryanCrotaz** [Apollo3zehn/FluentModbus#29]
System.TypeLoadException: Could not set up parent class, due to:  assembly:/home/pi/share/System.Private.CoreLib.dll type:Object member:(null)

**Comment by Apollo3zehn** [comment]
Thanks for reporting this issue. Could you please post the output of `dotnet --info` and a short sample code that causes the error? I will have access to a Raspi earliest on Friday. The SerialPort class should be available on Raspberry/ARM, too (according to a short Google search).

**Comment by BryanCrotaz** [comment]
I’ve just had to replace it with SerialPortStream from NuGet in another
project for that reason.

Bryan Crotaz
Silver Curve

On 19 Aug 2020, at 20:56, Apollo3zehn <notifications@github.com> wrote:

﻿

Thanks for reporting this issue. Could you please post the output of dotnet
--info and a short sample code that causes the error? I will have access to
a Raspi earliest on Friday. The SerialPort class should be available on
Raspberry/ARM, too (according to a short Google search).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Apollo3zehn/FluentModbus/issues/29#issuecomment-676629870>,
or unsubscribe

**Comment by BryanCrotaz** [comment]
Turned out to be something else in my build process
