### ISSUE TITLE
Remove private protected

### ISSUE THREAD

**Issue by robeving** [Apollo3zehn/FluentModbus#36]
Having this marked as private protected is annoying is it means I can't implement my own ModbusServer instance handling my custom transport layer

https://github.com/Apollo3zehn/FluentModbus/blob/ca56ca4c3d6f0a364b277fb37d5f076828e7908a/src/FluentModbus/Server/Mo
dbusServer.cs#L297

**Comment by Apollo3zehn** [comment]
You are right, that should be made accessible. Do you only need that method unprotected? If yes I will create an update tomorrow morning.

**Comment by robeving** [comment]
Also thanks for the library, works well for me!
