### ISSUE TITLE
Connect fails if port is not specified

### ISSUE THREAD

**Issue by seikosantana** [Apollo3zehn/FluentModbus#69]
I am using ModbusTCP client to connect to an IP address
`_modbusTcpClient.Connect("192.168.100.68", ModbusEndianness.BigEndian);`

It fails if I don't add `:502` after the IP address.
Is this expected behavior, since it says default port is 502?

Thanks in advance

**Comment by Apollo3zehn** [comment]
You are right l, this should work without adding a port. I will investigate it on Monday.

**Comment by Apollo3zehn** [comment]
This is fixed now in version v4.0.0-preview.3.
