### ISSUE TITLE
RTU over TCP

### ISSUE THREAD

**Issue by puschie286** [Apollo3zehn/FluentModbus#99]
Hi, do you plan to add RTU over TCP support ? its the last thing we need to replace other packages with fluentmodbus
( [some informations about it](https://github.com/NModbus/NModbus/issues/5) )

**Comment by Apollo3zehn** [comment]
I do not have much spare time for this project so a pull request would help to speed up bringing this features :-)

**Comment by Apollo3zehn** [comment]
I have never used RTU over TCP so I cannot give you any input about this. But it would be great if you work on a PR to add this feature!

**Comment by schotime** [comment]
@Apollo3zehn just in case you didn't see, but I submitted the PR, and it's been running for a couple weeks now from a local build. Let me know if there is anything else you need to me to change

**Comment by Apollo3zehn** [comment]
Thank you, I`ll check it today

**Comment by Apollo3zehn** [comment]
Closed by #126
